highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://fhkingma.github.io/joostkingma.github.io/
author: Friso Kingma

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /joostkingma.github.io/
title: Joost Kingma's Curriculum Vitae
name: Dr. Ir. J.H. Kingma
email: info@joostkingma.nl
email_full: mailto:info@joostkingma.nl
#website: github.io/sustain
#website_full: https://jekyllt.github.io/sustain
#github: trending
#twitter: twitter
birthdata: 28 december 1950
birthplace: Kortenhoef (NH)
tel: +31 343 410794
tel_full: tel:+31 343 410794
mobile: +31 6 53321864
mobile_full: tel:+31 6 53321864
google_maps: 'https://goo.gl/maps/tiRBxRcj4sofKaBR9'
address:
  street: Park Welgelegen 21
  postcode: 3971 KN
  city: Driebergen
#  country: Nederland
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
